<div class="html">
    <div class="body">
<div id="rendered-md"><ul>
<li>An exception is a way of handling an error that might occur when your program is running.</li>
<li>In order to throw an exception, you can use error numbers. E.g. <code class="inline-code">throw 99;</code>.</li>
<li>To handle the error, you need to catch the error (Which is the error number).</li>
<li>This is done using the <code class="inline-code">catch</code> keyword and enter a block of code to run if an error occurs.</li>
</ul>
<div class="joplin-editable"><pre class="joplin-source" data-joplin-language="cpp" data-joplin-source-open="```cpp&#10;" data-joplin-source-close="&#10;```">try {
    int num1 = 55;
    int num2 = 0;
    
    if(num1 &gt; num2) {
        throw 0;
    }
} catch(int x) {
    cout &lt;&lt; &quot;Math error: cannot divide by &quot; &lt;&lt; x &lt;&lt; endl;
} </pre><pre class="hljs"><code><span class="hljs-keyword">try</span> {
    <span class="hljs-type">int</span> num1 = <span class="hljs-number">55</span>;
    <span class="hljs-type">int</span> num2 = <span class="hljs-number">0</span>;
    
    <span class="hljs-keyword">if</span>(num1 &gt; num2) {
        <span class="hljs-keyword">throw</span> <span class="hljs-number">0</span>;
    }
} <span class="hljs-built_in">catch</span>(<span class="hljs-type">int</span> x) {
    cout &lt;&lt; <span class="hljs-string">&quot;Math error: cannot divide by &quot;</span> &lt;&lt; x &lt;&lt; endl;
} </code></pre></div>
<ul>
<li>To catch any error in your program, use <code class="inline-code">...</code> as an arguement for <code class="inline-code">catch</code> 'function'. E.g. <code class="inline-code">catch(...)</code></li>
</ul>
</div></div>
    </div>
</div>